from pydantic import BaseModel, Field, field_validator
from typing import Optional, Literal
from bson import ObjectId
from enum import Enum
import time


class FeedbackRating(str, Enum):
    """Binary rating values for user feedback on AI responses."""
    GOOD = "good_response"
    BAD = "bad_response"


class FeedbackSchema(BaseModel):
    """
    Feedback record for user ratings on AI responses.
    
    **Field Initialization:**
    - feedbackId: Auto-generated as MongoDB ObjectId on creation
    - createdAt: Auto-set to server timestamp (milliseconds since epoch)

    """
    feedbackId: str = Field(
        default_factory=lambda: str(ObjectId()),
        description="Unique MongoDB ObjectId identifier for this feedback record"
    )
    responseId: str = Field(
        ..., 
        min_length=1, 
        description="Foreign key reference to the chat response being rated"
    )
    sessionId: str = Field(
        ..., 
        min_length=1,
        description="Foreign key reference to the parent chat session"
    )
    userId: str = Field(
        ..., 
        min_length=1,
        description="User ID of who submitted this feedback (from authentication context)"
    )
    rating: Literal["good_response", "bad_response"] = Field(
        ..., 
        description="Binary feedback rating indicating response quality"
    )
    comment: Optional[str] = Field(
        None, 
        max_length=300,
        description="Optional user comment explaining rating (auto-trimmed to 300 chars)"
    )
    createdAt: int = Field(
        default_factory=lambda: int(time.time() * 1000),
        description="Server timestamp when feedback was submitted (milliseconds since Unix epoch)"
    )
    usedForTraining: bool = Field(
        default=False, 
        description="Flag indicating if this feedback has been exported for model fine-tuning"
    )

    @field_validator("comment", mode="before")
    @classmethod
    def strip_comment(cls, v: Optional[str]) -> Optional[str]:
        """Strip whitespace and enforce max length on comments."""
        if v is None:
            return None
        v = v.strip()
        if not v:
            return None
        # Truncate to 300 chars as additional safety measure
        return v[:300]

    @field_validator("rating")
    @classmethod
    def validate_rating(cls, v: str) -> str:
        """Ensure rating is one of the allowed values."""
        if v not in ("good_response", "bad_response"):
            raise ValueError(f"Rating must be 'good_response' or 'bad_response', got '{v}'")
        return v

    class Config:
        json_schema_extra = {
            "example": {
                "feedbackId": "507f1f77bcf86cd799439011",
                "responseId": "507f1f77bcf86cd799439012",
                "sessionId": "507f1f77bcf86cd799439013",
                "userId": "user123",
                "rating": "good_response",
                "comment": "Very helpful and accurate response!",
                "createdAt": 1699900000000,
                "usedForTraining": False,
            }
        }


class FeedbackStatsSchema(BaseModel):
    """
    Analytics schema for feedback statistics.
    """
    
    totalFeedback: int = Field(
        ...,
        description="Total number of feedback records included in these statistics"
    )
    goodCount: int = Field(
        ...,
        description="Number of 'good_response' ratings"
    )
    badCount: int = Field(
        ...,
        description="Number of 'bad_response' ratings"
    )
    goodPercentage: float = Field(
        ...,
        description="Percentage of good ratings (0-100)"
    )
    badPercentage: float = Field(
        ...,
        description="Percentage of bad ratings (0-100)"
    )

    class Config:
        json_schema_extra = {
            "example": {
                "totalFeedback": 150,
                "goodCount": 120,
                "badCount": 30,
                "goodPercentage": 80.0,
                "badPercentage": 20.0,
            }
        }


class FeedbackExportSchema(BaseModel):
    """
    Schema for fine-tuning dataset export (JSONL compatible).
    """
    
    prompt: str = Field(
        ..., 
        description="Original user message/question"
    )
    completion: str = Field(
        ..., 
        description="Assistant response generated by the model"
    )
    feedback: Literal["good", "bad"] = Field(
        ..., 
        description="Binary quality feedback: 'good' or 'bad'"
    )
    comment: Optional[str] = Field(
        None, 
        description="Optional user comment providing context for the feedback"
    )

    class Config:
        json_schema_extra = {
            "example": {
                "prompt": "What is MeTTa?",
                "completion": "MeTTa is a symbolic AI language designed for knowledge representation...",
                "feedback": "good",
                "comment": "Clear and concise explanation",
            }
        }
